[package]
name = "mcp-core"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
ai-runtime = { path = "../ai-runtime" }
mcp-vsock-transport = { path = "../mcp-vsock-transport" }
logging = { path = "../logging" }
