[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[tasks.build-all]
description = "Compila todo el workspace en release"
command = "cargo"
args = ["build", "--workspace", "--release"]

[tasks.image]
description = "Genera imagen de microVM (requiere xtask)"
command = "cargo"
args = ["run", "-p", "xtask", "--", "image"]

[tasks.qemu]
description = "Lanza QEMU con el kernel"
command = "cargo"
args = ["run", "-p", "xtask", "--", "qemu"]

[tasks.firecracker]
description = "Lanza Firecracker con la imagen"
command = "cargo"
args = ["run", "-p", "xtask", "--", "firecracker"]
