[package]
name = "drivers_virtio"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[lib]
crate-type = ["rlib"]

[features]
default = []
virtio-log = []
kernel = []

[dependencies]
logging = { path = "../logging" }
